# サーバーポート設定
server:
  address: 0.0.0.0
  port: 8080
spring:
  mvc:
    servlet:
      path: /api
  datasource:
    # データベースドライバークラス名
    driver-class-name: com.mysql.cj.jdbc.Driver
    # データベース接続URL
    url: jdbc:mysql://localhost:3306/rms_db
    # データベースユーザー名
    username: root
    # データベースパスワード
    password: 123456
  jackson:
    default-property-inclusion: NON_NULL

mybatis:
  configuration:
    # MyBatisのログ実装、標準出力に設定
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # MyBatis設定、データベースのアンダースコア命名をキャメルケースに自動変換
    map-underscore-to-camel-case: true

# Spring JDBCトランザクションマネージャーのログレベルをdebugに設定
logging:
  level:
    org:
      springframework:
        jdbc:
          support:
            JdbcTransactionManager: DEBUG  # Spring JDBC トランザクションマネージャーのログ
      apache:
        ibatis: DEBUG  # MyBatis のログ
      mybatis: DEBUG  # MyBatis コアのログ
    jdbc:
      sql: DEBUG  # SQL 実行の詳細ログ
      resultset: TRACE  # 結果セットの詳細ログ